version: "3"

services:
    flask_app:
        build: .
        restart: always
        ports:
            - "80:8000"
        environment:
            POSTGRES_DB: "packlotus"
            POSTGRES_PASSWORD: "123456789"
        links:
            - postgres
        depends_on:
            - postgres
        container_name: packalotus

    postgres:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_DB: "packlotus"
            POSTGRES_PASSWORD: "123456789"
        volumes:
            - .postgres-data:/var/lib/postgresql/data
        container_name: flask_postgres